[tool.poetry]
name = "modeltools"
version = "0.4.1"
description = ""
authors = ["Juan Ram√≠rez <juanseraar@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
