name: Building # Nombre del workflow
on: [push]
jobs: # Solo vamos a crear uno
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Copiamos el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry 
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Testing
        run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov --cov-report=xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test            # Name of the check run which will be created
          path: jest-junit.xml    # Path to test results
          reporter: java-junit        # Format of test results
      - name: Coverage Report
        if: always()
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage.lcov
          min_coverage: 90
          token: ${{ github.token }}
      - name: build
        run: poetry build
      - name: Publish to GH Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*